aliases:
  - &dependency-cache v1-dependencies-{{ checksum "pom.xml" }}
  - &ruby-cache v1-ruby-dependencies-{{ checksum "gendocs.rb" }}
  - &scala-cache v1-scala-test-dependencies-{{ checksum "scala/build.sbt" }}
version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/javatest
    environment:
      SBT_VERSION: 1.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - *dependency-cache
      - restore_cache:
          keys:
          - *scala-cache
      - run:
          name: Test Java and Install
          command: mvn -P local-install install
      - save_cache:
          paths:
            - ~/.m2
          key: *dependency-cache
      - run:
          # TODO why can't we have an image with this pre-installed??
          name: Install sbt
          command: |
            curl -L -o sbt-${SBT_VERSION}.deb https://dl.bintray.com/sbt/debian/sbt-${SBT_VERSION}.deb
            sudo dpkg -i sbt-${SBT_VERSION}.deb
            rm sbt-${SBT_VERSION}.deb
            sudo apt-get install sbt
      - run:
          name: Add local maven repository to SBT
          command: |
            mkdir -p ~/.sbt/1.0/
            touch ~/.sbt/1.0/global.sbt
            echo "resolvers += Resolver.mavenLocal" >> ~/.sbt/1.0/global.sbt
      - run:
          name: Compile Scala
          command: cd scala && sbt +compile
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt # Cache SBT Compiler interface
          key: *scala-cache
      - run:
          name: Test Scala
          command: cd scala && sbt +core/test:run && sbt +publishLocal && cd sbt-test && sbt +test

  jshellDocs:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/javatest
    steps:
      - checkout
      - restore_cache:
          keys:
          - *dependency-cache
      - run:
          name: Generate JShell Documentation
          command: ./run-jshell-docs.sh
      - persist_to_workspace:
          root: javatest/javatest-core/docs/jshell/output
          paths:
            - jshell-output

  docTest:
    docker:
      - image: circleci/ruby:2.6.0
    working_directory: ~/javatest
    environment:
      GEM_HOME: ~/gems
    steps:
      - checkout
      - restore_cache:
          keys:
          - *ruby-cache
      - attach_workspace:
          at: javatest/javatest-core/docs/jshell/output
      - run:
          name: Install AsciiDoctor
          command: sudo gem install asciidoctor --conservative
      - save_cache:
          key: *ruby-cache
          paths:
            - ~/gems
      - run:
          name: Test no diff
          command: |
            ruby gendocs.rb
            if [ -z "$(git status --porcelain)" ]; then
              echo "No changes to documentation"
            else
              echo "Documentation has changed, please rerun 'ruby gendocs.rb' and commit the changes"
              git --no-pager diff
              exit 1
            fi

workflows:
  version: 2
  test:
    jobs:
      - test
      - jshellDocs
      - docTest:
          requires:
            - jshellDocs
