aliases:
  - &dependency-cache v1-dependencies-{{ checksum "pom.xml" }}
  - &ruby-cache v1-ruby-dependencies-{{ checksum "gendocs.rb" }}
  - &scala-cache v1-scala-dependencies-{{ checksum "scala/build.sbt" }}
  - &clojure-cache v1-clojure-test-dependencies-{{ checksum "clojure/project.clj" }}
version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
    working_directory: ~/javatest
    environment:
      SBT_VERSION: 1.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - *dependency-cache
      - restore_cache:
          keys:
          - *scala-cache
      - restore_cache:
          keys:
          - *clojure-cache
      - run:
          name: Test Java and Install
          command: mvn -P local-install install
      - save_cache:
          paths:
            - ~/.m2
          key: *dependency-cache
      - run:
          # TODO why can't we have an image with this pre-installed??
          name: Install sbt
          command: |
            curl -L -o sbt-${SBT_VERSION}.deb https://dl.bintray.com/sbt/debian/sbt-${SBT_VERSION}.deb && \
            sudo dpkg -i sbt-${SBT_VERSION}.deb && \
            rm sbt-${SBT_VERSION}.deb && \
            sudo apt-get install sbt
      - run:
          name: Compile Scala
          command: cd scala && sbt compile
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt # Cache SBT Compiler interface
          key: *scala-cache
      - run:
          name: Test Scala
          command: cd scala && sbt test:run
      - run:
          name: Test Clojure
          command: cd clojure && lein run -m javatest-clj.tests
      - save_cache:
          paths:
            - ~/.m2
          key: *clojure-cache

  docTest:
    docker:
      - image: circleci/ruby:2.6.0
    working_directory: ~/javatest
    environment:
      GEM_HOME: ~/gems
    steps:
      - checkout
      - restore_cache:
          keys:
          - *ruby-cache
      - run:
          name: Install AsciiDoctor
          command: sudo gem install asciidoctor --conservative
      - save_cache:
          key: *ruby-cache
          paths:
            - ~/gems
      - run:
          name: Test no diff
          command: |
            ruby gendocs.rb
            if [ -z "$(git status --porcelain)" ]; then
              echo "No changes to documentation"
            else
              echo "Documentation has changed, please rerun 'ruby gendocs.rb' and commit the changes"
              exit 1
            fi

workflows:
  version: 2
  test:
    jobs:
      - test
      - docTest
