aliases:
  - &dependency-cache v1-dependencies-{{ checksum "pom.xml" }}
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/javatest
    steps:
      - checkout
      - restore_cache:
          keys:
          - *dependency-cache
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # TODO Find out how to get dependency:go-offline to work with multi-module. It's fine for now since it only depends on the JDK.
      - run: mvn dependency:resolve-plugins
      - save_cache:
          paths:
            - ~/.m2
          key: *dependency-cache
      - run: mvn test