= JavaTest
:toc: macro
:toc-title:
:note-caption: :information_source:

--
image::https://circleci.com/gh/olib963/javatest.svg?style=svg[link="https://circleci.com/gh/olib963/javatest", float="left"]
image::https://img.shields.io/maven-central/v/io.github.olib963/javatest-core.svg?style=plastic[link="http://mvnrepository.com/artifact/io.github.olib963/javatest-core", float="left"]
--

NOTE: *Fair Warning*: The entirety of this project should currently be considered alpha and subject to change. I am sure I have not got the API or library right on the first try so there may be breaking changes in the future.

== Overview

An opinionated, functional test framework written in pure Java aiming to leverage newer features of the Java language and give
power back to the test writer. Based on these ideas:

* If you know how to write a Java application, I think you should automatically know how to write the tests,
therefore JavaTest only introduces a few new functions and types to the language, there is no new syntax.

* Instead of being *Annotation* and *Exception* driven, JavaTest is *Function* and *Value* driven,
lending itself to composability of tests and assertions.

* JavaTests contains no reflection magic. A more declarative approach to testing is taken where setting up and customising tests is left
to the writer.

* A test should ideally only test one thing and should certainly test _at least_ one thing. Since
all tests must return an assertion value the compiler will enforce that all tests only test one result.

* Tests should be easy to understand and enjoyable to write, after all we all spend a lot of our time working on them :D

== Quick Start

=== I'm new to Java

.Expand
[%collapsible]
====

Download the latest jar artifact of JavaTest Core from the https://github.com/olib963/javatest/releases[release page].
Then create these files in your project directory:

1. `foo/Calculator.java`
+
This is the System Under Test representing the source code for your application (in this case a calculator that can add integers)
+
[source, java]
----
include::../src/test/java/foo/Calculator.java[]
----

2. `foo/Tests.java`
+
This file is a java executable containing tests for our SUT, it exists in the same package so there is no need to
`import foo.Calculator;`.
+
This example defines two simple tests, one is testing that `1 + 1 = 2` by
simply using the java `+` function and the other test checks our calculator gets the same result. We then
invoke the `runTests` function to run our tests and check if they passed.
+
[source, java]
----
include::../src/test/java/foo/Tests.java[]
----
+
Note how for the second test the assertion description includes all the information required to tell is what
has gone wrong if our tests are failing.
+
You can then run from the commandline:
+
[source, bash]
----
# Compile both Java classes ensuring JavaTest and the current directory are both on the class path
javac -cp "/absolute/path/to/javatest/jar:." foo/Calculator.java foo/Tests.java

# Run the "Tests" executable ensuring JavaTest and the current directory are both on the class path
java -cp "/absolute/path/to/javatest/jar:." foo.Tests
----
+
These tests should currently fail with a nice error message. You should be able to fix the calculator and see your tests pass.

Notes:

* You will need to use `;` to separate classpath entries instead of `:` on windows machines

* You will need to include at least the JavaTest jar and the current directory (`.`) on the classpath in order for this to work,
if you are using java classes from any other jars/directories you will need to also ensure they are on the classpath.

You should be able to explore the <<Core Library,Core Library>> and get familiar with testing your code by running them from
an executable.

====

=== I know Java pretty well

.Expand
[%collapsible]
====

An example of a test entry point:

[source, java]
----
include::../../javatest-fixtures/src/test/java/io/github/olib963/javatest/fixtures/documentation/MyRunners.java[tags=include]
----

An example of a test suite:

[source, java]
----
include::../../javatest-fixtures/src/test/java/io/github/olib963/javatest/fixtures/documentation/MyFirstUnitTestSuite.java[tags=include]
----

These tests can be run in a few different ways, look into <<Running JavaTest,Running JavaTest>> to find the way that works
best for you.

The <<Core library,Core library>> section explains the fundamentals of how these tests are defined. Functionality from
the Fixtures and Matchers modules are used in this example, explore the <<Module List,Module List>> to see if there are
any extensions that fit your needs.

If there is something you cannot achieve with the existing functionality please open an issue describing what you want to do :D

====

'''

[discrete]
== Contents

toc::[]

== Core Library

* `JavaTest`: the entrypoint class. It contains the main `run` function as well as static factory functions to define tests
* `TestRunner`: implements the running of tests and returns `TestResults`
* `Testable`: wrapper around one of:
** `Test`: a named instance of a test, each test must return an `Assertion`
** `TestSuite`: a named logical collection of ``Testable``s
* `Assertion`: represents the expected state at the end of a test
* `TestResults`: represents the combined result of your tests

=== Creating Assertions

The core ``Assertion``s are created simply from boolean expressions and a string description. If the boolean condition is `true` then
the `Assertion` is said to "hold".

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyAssertions.java[tags=include]
----

=== Composing Assertions

``Assertion``s can be composed using the `and`, `or` and `xor` default methods. These are all examples of composed ``Assertion``s
that hold (i.e. will pass tests):

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyComposedAssertions.java[tags=include]
----

In the case where you have _many_ assertions (perhaps a large list) I would suggest using the `all` assertion
functionality for a more better output:

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyAllAssertions.java[tags=include]
----

=== Test Definitions

A JavaTest `Test` is defined by:

* A name
* A `Supplier` of an `Assertion`

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyTests.java[tags=include]
----

The test will fail if the `Supplier` throws any exception at all. Please see <<Notes,Notes>> for information on ``AssertionError``s.

=== Test Suites

You can group your ``Test``s into logical units using ``TestSuite``s.

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyFirstTestSuite.java[tags=include]
----

==== Suite Classes

A common use case will be to use a class to store your tests, to do this simply implement `TestSuiteClass`. Your class
will then be able to be used anywhere you would use a `Testable` e.g. adding to another `TestSuite` or passing
to JavaTests run functions. The name of the suite will be the name of the class.

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/ClassAsSuite.java[tags=include]
----

==== Suite Nesting

``TestSuite``s contain ``Testable``s not ``Test``s and thus can even be contain other ``TestSuite``s.

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/SuiteOfSuites.java[tags=include]
----

=== Pending Tests

Sometimes it will be useful to define a bunch of `Test` cases ahead of implementing them, this is where
pending ``Assertion``s come in. They will not fail your build but will logged in a different colour than successes/failures
if using the coloured logger. You can optionally provide a reason this `Test` has not yet been written.

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyPendingTests.java[tags=include]
----

=== Test Runners

The main `TestRunner` included in the core is created from a `Collection<Testable>`. You can optionally add a collection of
``TestCompletionObserver``s to the runner, by default a logging observer is passed that logs each test result with a colour
corresponding to the state of the test (green for passing, red for failing and yellow for pending). If you want to turn off
logging just pass an empty collection, a `TestCompletionObserver.plainLogger` also exists that uses no colours.

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/RunnerDocumentation.java[tags=normal-imports]
include::../src/test/java/io/github/olib963/javatest/documentation/RunnerDocumentation.java[tags=imports]

include::../src/test/java/io/github/olib963/javatest/documentation/RunnerDocumentation.java[tags=normal, indent=-]
----

Other `TestRunner` implementations are available in the other modules.

==== Laziness

It is possible to create a lazy test runner from a `Stream<Testable>` also with optional collection of ``TestCompletionObserver``s.
This runner however is not referentially transparent or reusable so must be used with care. This might be useful if you have
a very large collection of tests and you want to lazily instantiate the different suites.

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/RunnerDocumentation.java[tags=lazy-imports]
include::../src/test/java/io/github/olib963/javatest/documentation/RunnerDocumentation.java[tags=imports]

include::../src/test/java/io/github/olib963/javatest/documentation/RunnerDocumentation.java[tags=lazy, indent=-]
----

=== Core library maven dependency

[source, xml]
----
<dependency>
    <groupId>io.github.olib963</groupId>
    <artifactId>javatest-core</artifactId>
    <version>${javatest.version}</version>
    <scope>test</scope>
</dependency>
----

== Running JavaTest

=== In Java

To run JavaTest simply pass your `TestRunner` instances to the `JavaTest.run()` function and handle the
result how you see fit. There is a convenience function `runTests` defined to just run a `Collection<Testable>` using the default `CollectionRunner`:

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/MyEntrypoint.java[tags=include]
----

==== Observer

There is an interface `TestRunCompletionObserver` that exists to allow side effects to be invoked after the run has completed.
By default the total counts of tests run will be logged to `System.out`. If you want to turn off logging simply pass an empty
collection of observers to the `run` function i.e. `JavaTest.run(runners, Collections.emptyList())`.

=== With JavaFire Maven plugin

If you are using https://maven.apache.org/[maven] you can add the `JavaFire` maven plugin to your pom
to run your tests during mavens `test` phase. By default this will use the link:javatest/javatest-reflection[Reflection Module]
to run any instances of `TestSuiteClass` or `TestRunners` in your test source directory that have a *public zero argument constructor*.

[source, xml]
----
<plugin>
    <groupId>io.github.olib963</groupId>
    <artifactId>javafire-maven-plugin</artifactId>
    <version>${javatest.version}</version>
    <executions>
        <execution>
            <id>test</id>
            <goals>
                <goal>test</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

Alternatively you can run tests defined by a single `TestRunners` class. Your `TestRunners` class _must_ have a *public zero argument constructor*.
This is achieved by passing the class name to the plugin configuration for example:

[source, java]
----
package my.awesome.app;

include::../../javatest-fixtures/src/test/java/io/github/olib963/javatest/fixtures/documentation/MyRunners.java[tags=include]
----

In `pom.xml`:

[source, xml]
----
<plugin>
    <groupId>io.github.olib963</groupId>
    <artifactId>javafire-maven-plugin</artifactId>
    <version>${javatest.version}</version>
    <configuration>
        <testRunners>my.awesome.app.MyRunners</testRunners>
    </configuration>
    <executions>
        <execution>
            <id>test</id>
            <goals>
                <goal>test</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

You can override the `testRunners` class being used by setting the maven property e.g. `mvn -Djavafire.testRunners=com.my.app.OtherTests test`.

=== JShell

Since JavaTest is built on pure Java it plays quite nicely with the REPL. This startup script may be useful to you:

.javatest-startup-script.jsh
[source, jshelllanguage]
----
include::./jshell/startup-script-template.jsh[]
----

Then you can run:

[source, bash]
----
~$ jshell --startup DEFAULT --startup javatest-startup-script.jsh
include::./jshell/output/jshell-output[]
----

== Maven Integration

If you are using maven there is a bill of materials you can import to manage the versions of dependencies. You can
add this to your pom by doing the following?

.pom.xml
[source, xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.github.olib963</groupId>
            <artifactId>javatest-bom</artifactId>
            <version>${javatest.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependencies>
    <dependency>
        <groupId>io.github.olib963</groupId>
        <artifactId>javatest-core</artifactId>
    </dependency>
    <dependency>
        <groupId>io.github.olib963</groupId>
        <artifactId>javatest-matchers</artifactId>
    </dependency>
    <!-- ... More dependencies -->
</dependencies>
----

== Module List

JavaTest is built on a simple functional core and functionality is expanded on by several modules found here:

* link:javatest/javatest-matchers[Matchers]
* link:javatest/javatest-fixtures[Fixtures]
* link:javatest/javatest-parameterised[Parameterised Testing]
* link:javatest/javatest-benchmark[Benchmarking]
* link:javatest/javatest-eventually[Eventual Consistency]
* link:javatest/javatest-junit[JUnit]
* link:javatest/javatest-reflection[Reflection]
* link:scala[Scala]

== Functional Interfaces

Where possible interfaces are ``@FunctionalInterface``s so can be replaced with lambdas when you feel it fits. This is true for:

* ``Assertion``s

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/functions/FunctionalAssertions.java[tags=include]
----

* ``TestRunner``s

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/functions/FunctionalRunners.java[tags=include]
----

* ``TestCompletionObserver``s and ``TestRunCompletionObserver``s

[source, java]
----
include::../src/test/java/io/github/olib963/javatest/documentation/functions/FunctionalObservers.java[tags=include]
----

In the cases where this is not possible (e.g. ``Matcher``s or ``FixtureDefinition``s) static factories will be
provided to construct an instance of the interface from appropriate functions.

== Feedback

Any feedback/constructive criticism is appreciated. Please open an issue if you have any suggestions.

== Notes

* Documentation is built using https://asciidoctor.org[asciidoctor] such that all documentation snippits can be both compile time checked
and tested.

* If a test throws an `AssertionError` instead of returning an `Assertion` the library will ignore the error message and instead
tell you to "return an Assertion". This will stop you from trying to add in extra assertions using something like the JUnit
`assertX` functions in the middle of your test.

* Currently there is no way to programmatically find the source location of a test/suite. This is a challenge I am going to attempt to
tackle once I implement an IDE plugin.
