= JavaTest Scala
:note-caption: :information_source:

JavaTest is an opinionated, functional test framework written in pure Java, this module provides a wrapper around the underlying
java framework that provides a more idiomatic Scala interface. Syntax can be selectively imported by mixing the appropriate
trait e.g. `FixtureSyntax`, however, if you want all functions to be in scope simply `import io.github.olib963.javatest_scala._`.

The general idea is to apply functional programming principles to test code as well as source code. Tests, Suites, Fixtures
etc. are all defined as data that you can operate on rather than Object Oriented classes for which you must implement behaviours
and inheritance trees.

== Core functionality

A `Test` in JavaTest is defined by a string name and a function of type `() => Assertion`. You can create

* a simple `Assertion` from a `Boolean` and a `String`
* a `Matcher` based assertion (see <<Matchers,Matchers>>)

[source, scala]
----
test("Passing multiline test"){
  val word = "HELLO WORLD"
  val expected = "hello world"
  val actual = word.toLowerCase()
  that(actual == expected, s"Expected $word to lower case to be $expected (was $actual)")
}
----

=== Suites

Test suites are constructed from a `String` name and a `Seq` of ``Test``s or nested ``Suite``s. ``Suite``s can be constructed from:

- Varags:

[source, scala]
----
val suiteFromVarargs = suite("My Vararg Suite",
  test("simple test")(that(true, "passing")),
  test("addition test")(that(1 + 1 == 2, "One add one is two"))
)
----

- `Seq[Testable]` (this is useful for programmatically generated tests):

[source, scala]
----
val multiplesOf9 = Map(
  1 -> 9,
  2 -> 18,
  7 -> 63,
  456 -> 4104)

val suiteFromSeq = suite("Multiples of 9 suite",
  multiplesOf9.map {
    case (multiple, expected) =>
      test(s"The ${multiple}th multiple of 9") {
        val result = multiple * 9
        that(result == expected, s"Should be $expected (was $result)")
      }
  }.toSeq
)
----

- Traits:

[source, scala]
----
object MySuite extends Suite with JavaTestSyntax {
  override def tests: Seq[Testable] = Seq(
    suite("Nested Suite",
      test("simple test")(that(true, "passing"))
    ),
    test("addition test")(that(1 + 1 == 2, "One add one is two"))
  )
}
----

=== Test Runners

An implicit transformation exists to turn a `Seq[Testable]` into a `TestRunner`. Alternatively you can customise the test
runner by overriding the default test observer.

[source, scala]
----
val runner: TestRunner = Seq(
  suite("My Suite",
    test("test1")(that(true, "passes")),
    test("test2")(that(true, "passes"))
  )
)

// Or to run directly
run(
  Seq(
    suite("My Suite",
      test("test1")(that(true, "passes")),
      test("test2")(that(true, "passes"))
    )
  )
)

// Custom Runner
val customRunner = testableRunner(
  Seq(
    suite("My Suite",
      test("test1")(that(true, "passes")),
      test("test2")(that(true, "passes"))
    )
  ),
  // Observer function: (TestResult => Unit)
  result => println(result)
)
----

== Matchers

``Matcher``s can be used in this module the same way as in Java. They provide the descrption and predicate check required for
an ``Assertion``. Only a few matchers are available by default. I hope to expand on this functionality in the future.

[source, scala]
----

import io.github.olib963.javatest.Testable

import scala.util.{Failure, Success}

object MatcherTests extends Suite with JavaTestSyntax with MatcherSyntax {
  override def tests: Seq[Testable] = Seq(
    test("Equal")(that(List(1, 2, 3), isEqualTo(List(1, 2, 3)))),
    test("Type")(that("foo", hasType[String])),
    test("Instance") {
      val javaObject = new Object()
      that(javaObject, isTheSameInstanceAs(javaObject))
    },
    test("String starts with")(that("hello world", startsWith("hello"))),
    test("String ends with")(that("hello world", endsWith("world"))),
    test("String contains string")(that("hello world", containsString("o w"))),
    test("String empty")(that("", isEmptyString)),
    test("String whitespace")(that("\t\n", isBlankString)),
    test("String equal ignore case")(that("HeLlO WoRlD", isEqualToIgnoringCase("hElLo wOrLd"))),
    test("String length")(that("hello world", hasLength(11))),
    test("With custom message")(that("Because my string is empty", "", isBlankString))
  )
}


object ScalaSpecificMatcherTests extends Suite with JavaTestSyntax with MatcherSyntax {
  override def tests: Seq[Testable] = Seq(
    suite("Option tests",
      suite("defined tests",
        // TODO it should not need the type hint. Probably some variance changes in the java API would fix it.
        test("isDefined")(that(Some(1), isDefined[Int])),
        test("isDefined (empty)")(that(None, not(isDefined)))
      ),
      suite("empty tests",
        test("isEmpty")(that(None, isEmptyOption)),
        test("isEmpty (not empty)")(that(Some(1), not(isEmptyOption[Int])))
      ),
      suite("contains tests",
        test("Contains")(that(Some(2), optionContains(2))),
        test("Contains (missing element)")(that(None, not(optionContains(4))))
      )
    ),
    suite("Collection tests",
      suite("empty tests",
        test("isEmpty")(that(Seq(), isEmpty)),
        test("isEmpty (not empty)")(that(Seq(1, 2, 3), not(isEmpty[Int])))
      ),
      suite("contains tests",
        test("contains")(that(Seq(1, 2, 3), contains(2))),
        test("contains (missing element)")(that(Seq(1, 2, 3), not(contains(4))))
      ),
      suite("hasSize tests",
        test("has size")(that(Seq(1, 2, 3), hasSize[Int](3))),
        test("has size (wrong size)")(that(Seq(1, 2, 3), not(hasSize[Int](4))))
      )
    ),
    suite("Try tests",
      suite("success tests",
        test("isSuccess")(that(Success(10), isSuccess[Int])),
        test("isSuccess (with failure)")(that(Failure(new Exception()), not(isSuccess)))
      ),
      suite("failure tests",
        test("isSuccess")(that(Failure(new Exception()), isFailure)),
        test("isSuccess (with success)")(that(Success(10), not(isFailure[Int])))
      )
    )
  )
}
----

== Eventual Consistency

You can provide an `Assertion` that won't hold straight away to the `eventually` function. It accepts an implicit
`EventuallyConfig` that contains:

* The number of attempts to make before the assertion fails
* The `Duration` to wait between each attempt
* An optional initial `Duration` to wait before the first attempt

[source, scala]
----
test("custom config") {
  import scala.concurrent.duration._
  implicit val config: EventuallyConfig = EventuallyConfig(attempts = 5, waitInterval = 500.millis)
  val atomicInt = new AtomicInteger(0)
  executorService.submit(() => {
    Thread.sleep(1000)
    atomicInt.getAndIncrement()
  })
  eventually(that(atomicInt.get(), isEqualTo(1)))
})
----

== Fixtures

You can create a `FixtureDefinition[A]` from a function `() => Try[A]` with optional tear down function `A => Try[Unit]`.
You can then use this definition to create a test runner that makes use of the fixture.

[source, scala]
----
val mySimpleFixture: FixtureDefinition[String] = fixture(Success("Hello"))

val runnerUsingSimpleFixture = fixtureRunner("sting fixture", mySimpleFixture)(word =>
  test("Simple fixture")(that(word, isEqualTo("Hello")))
)
----

You can curry common fixtures you want to create multiple instances of:

[source, scala]
----
val myComplexFixture: FixtureDefinition[FileReader] =
  destructibleFixture(Try(new FileReader("myTestFile.txt")))(r => Try(r.close()))

// You can reuse fixture runners then later apply the function to create your tests
val reusableFixture: (FileReader => TestRunner) => TestRunner =
  fixtureRunner("test file reader", myComplexFixture)

val runner1 = reusableFixture { fileReader =>
  test("Character reading")(
    that("First character read from file", fileReader.read().toChar, isEqualTo('H')))
}

val runner2 = reusableFixture { aDifferentReader =>
  test("Content reading"){
    val builder = new StringBuilder
    var c = aDifferentReader.read()
    while (c != -1) {
      builder.append(c.toChar)
      c = aDifferentReader.read()
    }
    that("Contents read from test file", builder.toString, isEqualTo("Hello, test!"))
  }
}
----

== Benchmarking

To benchmark a `Test` or a `TestRunner` call the `benchmark` function, this will add the time of the test/run to the logs.
All benchmark functions accepts an implicit `DurationFormat` function that accepts scala ``Duration``s and return a `String`.

You can also set a time limit on a `Test` by using the `failIfLongerThan` function.

[source, scala]
----
val passingAssertion = that(true, "always passes")

val customFormattedTest = {
  implicit val customFormatter: DurationFormat = d => s"${d.toMillis}ms"
  benchmark(test("Benchmarked Test")(passingAssertion))
}

val timedTest = failIfLongerThan(2.seconds)(
  test("Test with time limit") {
    Thread.sleep(1.second.toMillis)
    passingAssertion
  }
)
----

== Scalacheck

Scalacheck integration is still in its very early stages, but you are able to use the scalacheck module to create property tests.

[source, scala]
----
import io.github.olib963.javatest_scala._
import io.github.olib963.javatest_scala.scalacheck._
import org.scalacheck.Gen

object ScalacheckSuite extends Suite {

  override def tests: Seq[Testable] = Seq(
    test("Pending scalacheck test")(
      forAll { s: String => pending("Not yet written") }
    ),
    test("Sqrt")(forAll(Gen.posNum[Int]) { n =>
      val m = math.sqrt(n.toDouble)
      that(s"Square root of $n squared is $n", math.round(m * m), isEqualTo[Long](n))
    }),
    suite("List Properties",
      test("List tail")(forAll { (n: Int, l: List[Int]) =>
        that("Tail of a list with a prepended element is the original list", (n :: l).tail, isEqualTo(l))
      }),
      test("List reverse")(forAll { l: List[String] =>
        val reversed = that(l.reverse.reverse, isEqualTo(l))
        if(l.size <= 1) reversed else reversed.and(that(l.reverse, not(isEqualTo(l))))
      }),
      test("List head")(forAll { l: List[Int] =>
        if (l.isEmpty) {
          that("Head of an empty list is empty", l.headOption, isEmptyOption[Int])
        } else {
          that("Head of non empty list is the first element", l.head, isEqualTo(l(0)))
        }
      })
    ),
  )
}
----

== SBT Integration

If you are using SBT you can add the following line to `plugins.sbt`. This will automatically run any ``object``s
in your test source directory that extends the `Suite` trait and any ``object``s that extend the `Runners` trait.

.plugins.sbt
[source, sbt]
----
addSbtPlugin("io.github.olib963" % "sbt-javatest" % javaTestVersion)
----

If instead you prefer to not use the SBT plugin and take over the execution of your tests yourself you can add the
library dependency:

.build.sbt
[source, sbt]
----
libraryDependencies += "io.github.olib963" %% "javatest-scala" % javaTestVersion % Test
----

You can then run your tests from any point in your code by invoking the `run` function on a `Seq[TestRunner]`. For example
this is how the test entrypoint is defined in the core project:

[source, scala]
----
package io.github.olib963.javatest_scala

import java.util.concurrent.Executors

import io.github.olib963.javatest.TestRunner
import io.github.olib963.javatest_scala.documentation._

import scala.util.Try

object MyTests {

  // The following line would be needed to inherit all syntax if we weren't already in that package
  // import io.github.olib963.javatest_scala._

  private val executorServiceFixture = destructibleFixture(Try(Executors.newFixedThreadPool(2)))(e => Try(e.shutdown()))

  def main(args: Array[String]): Unit = {
    val testRunner = fixtureRunner("executor", executorServiceFixture)(
      executor => Seq(SimpleTests, MatcherTests, ScalaSpecificMatcherTests, EventualTests(executor)))

    val results = run(benchmark(testRunner))

    if (!results.succeeded) {
      sys.error("Scala tests failed")
    }

    val documentationResults = run(
      Seq[TestRunner](
        FixtureDocumentation.runnerUsingSimpleFixture,
        FixtureDocumentation.runner1,
        FixtureDocumentation.runner2,
        BenchmarkDocumentation,
        SuiteDocs
      ) ++ MyRunners.Runners
    )

    if (!documentationResults.succeeded) {
      sys.error("Documentation tests failed")
    }
  }

}
----

=== Limitations of SBT Test Framework

- The command `sbt test` will run everything
- `sbt testQuick` will currently rerun every test not just the ones that have failed. Hopefully I will revisit the interface
implementation to handle this better in the future.
- You can run `sbt testOnly` as normal for ``Suite``s, however for instances of `Runners` the `testOnly` filtering will
only apply to the `Runners` object not any tests generated from them.

For example, if your source code was:
[source, scala]
----
object MyRunners extends Runners {
  override def Runners: Seq[TestRunner] = {

    val simpleRunner: TestRunner =
      Seq(
        suite("Suite1", test("test")(pending())),
        suite("Suite2", test("test")(pending()))
      )

    Seq(
      simpleRunner
      // Other runner definitions ...
    )
  }
}
----

Running `sbt testOnly *MyRunners` would run both "Suite1" and "Suite2" but no other ``object``s in your test code.
You cannot currently filter this further to say `sbt testOnly *MyRunners.Suite1`.