= JavaTest Scala
:note-caption: :information_source:

JavaTest is an opinionated, functional test framework written in pure Java, this module provides a wrapper around the underlying
java framework that provides a more idiomatic Scala interface. Syntax can be selectively imported by mixing the appropriate
trait e.g. `FixtureSyntax`, however, if you want all functions to be in scope simply `import io.github.olib963.javatest_scala._`.

The general idea is to apply functional programming principles to test code as well as source code. Tests, Suites, Fixtures
etc. are all defined as data that you can operate on rather than Object Oriented classes for which you must implement behaviours
and inheritance trees.

== Core functionality

A `Test` in JavaTest is defined by a string name and a function of type `() => Assertion`. You can create

* a simple `Assertion` from a `Boolean` and a `String`
* a `Matcher` based assertion (see <<Matchers,Matchers>>)

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/SimpleTests.scala[tags=include, indent=-]
----

=== Suites

Test suites are constructed from a `String` name and a `Seq` of ``Test``s or nested ``Suite``s. ``Suite``s can be constructed from:

- Varags:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/SuiteDocs.scala[tags=varargs, indent=-]
----

- `Seq[Testable]` (this is useful for programmatically generated tests):

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/SuiteDocs.scala[tags=seq, indent=-]
----

- Traits:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/SuiteDocs.scala[tags=trait, indent=-]
----

=== Test Runners

An implicit transformation exists to turn a `Seq[Testable]` into a `TestRunner`. Alternatively you can customise the test
runner by overriding the default test observer.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/RunnerDocs.scala[tags=definition, indent=-]

// Or to run directly
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/RunnerDocs.scala[tags=running, indent=-]

// Custom Runner
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/RunnerDocs.scala[tags=customDefinition, indent=-]
----

== Matchers

``Matcher``s can be used in this module the same way as in Java. They provide the descrption and predicate check required for
an ``Assertion``. Only a few matchers are available by default. I hope to expand on this functionality in the future.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/MatcherTests.scala[tags=include]

include::../core/src/test/scala/io/github/olib963/javatest_scala/MatcherTests.scala[tags=scala]
----

== Eventual Consistency

You can provide an `Assertion` that won't hold straight away to the `eventually` function. It accepts an implicit
`EventuallyConfig` that contains:

* The number of attempts to make before the assertion fails
* The `Duration` to wait between each attempt
* An optional initial `Duration` to wait before the first attempt

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/EventualTests.scala[tags=test, indent=-]
----

== Fixtures

You can create a `FixtureDefinition[A]` from a function `() => Try[A]` with optional tear down function `A => Try[Unit]`.
You can then use this definition to create a test runner that makes use of the fixture.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/FixtureDocumentation.scala[tags=simple, indent=-]
----

You can curry common fixtures you want to create multiple instances of:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/FixtureDocumentation.scala[tags=complex, indent=-]
----

== Benchmarking

To benchmark a `Test` or a `TestRunner` call the `benchmark` function, this will add the time of the test/run to the logs.
All benchmark functions accepts an implicit `DurationFormat` function that accepts scala ``Duration``s and return a `String`.

You can also set a time limit on a `Test` by using the `failIfLongerThan` function.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/BenchmarkDocumentation.scala[tags=include, indent=-]
----

== Scalacheck

Scalacheck integration is still in its very early stages, but you are able to use the scalacheck module to create property tests.

[source, scala]
----
include::../sbt-test/src/test/scala/my/app/ScalacheckSuite.scala[tags=imports, indent=-]

include::../sbt-test/src/test/scala/my/app/ScalacheckSuite.scala[tags=include, indent=-]
  )
}
----

== SBT Integration

If you are using SBT you can add the following line to `plugins.sbt`. This will automatically run any ``object``s
in your test source directory that extends the `Suite` trait and any ``object``s that extend the `Runners` trait.

.plugins.sbt
[source, sbt]
----
include::../sbt-test/project/plugins.sbt[tags=include]
----

If instead you prefer to not use the SBT plugin and take over the execution of your tests yourself you can add the
library dependency:

.build.sbt
[source, sbt]
----
libraryDependencies += "io.github.olib963" %% "javatest-scala" % javaTestVersion % Test
----

You can then run your tests from any point in your code by invoking the `run` function on a `Seq[TestRunner]`. For example
this is how the test entrypoint is defined in the core project:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/MyTests.scala[]
----

=== Limitations of SBT Test Framework

- The command `sbt test` will run everything
- You can run `sbt testOnly` and `sbt testQuick` as normal for ``Suite``s, however for instances of `Runners` the `testOnly` filtering will
only apply to the `Runners` object not any tests generated from them.

For example, if your source code was:
[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/MyRunners.scala[tags=include]
----

Running `sbt testOnly *MyRunners` would run both "Suite1" and "Suite2" but no other ``object``s in your test code.
You cannot currently filter this further to say `sbt testOnly *MyRunners.Suite1`.

The same applies for any failured ``Runners`` rerun by `sbt testQuick`
