= JavaTest Scala
:note-caption: :information_source:

This module provides a wrapper around the underlying java framework that provides a more idiomatic Scala interface. Syntax
can be selectively imported by mixing the appropriate trait e.g. `FixtureSyntax`, however, if you want all functions to be in scope
simply `import io.github.olib963.javatest_scala._`.

NOTE: Currently knowledge and understanding of the Java library is assumed. I will expand on these docs to be self-explanitory
at a later date.

== Core functionality

All core functionality remains essentially unchanged from the Java framework but has new syntax

Assertions and tests are defined the same as the Java syntax with the addition that the test function is now in a separate parameter list

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/SimpleTests.scala[tags=include, indent=-]
----

=== Suites

Suites can be constructed from:

- Varags:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/SuiteDocs.scala[tags=varargs, indent=-]
----

- `Seq[Testable]` (this is useful for programmatically generated tests):

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/SuiteDocs.scala[tags=seq, indent=-]
----

- Traits:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/SuiteDocs.scala[tags=trait, indent=-]
----

=== Runners

Runners can be generated the same way as in the java framework but an implicit transformation exists to turn
a `Seq[Testable]` into a `TestRunner`.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/RunnerDocs.scala[tags=definition, indent=-]

// Or to run directly
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/RunnerDocs.scala[tags=running, indent=-]
----

== Matchers

``Matcher``s can be used in this module the same way as in Java. Only a few matchers are available by default.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/MatcherTests.scala[tags=include]
----

I will be adding many Scala specific matchers in the future.

== Eventual Consistency

The eventual consistency assertions in this module take an implicit configuration and uses scala ``Duration``s instead of java ``Duration``s.
The default configuration is also supplied implicitly in the case you do not provide one.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/EventualTests.scala[tags=assertion, indent=-]
----

== Fixtures

Fixtures in this module make use of `scala.util.Try` and creating a runner is a multi-parameter list function.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/FixtureDocumentation.scala[tags=simple, indent=-]
----

You can create fixtures with a tear down method and curry common fixtures you want to create multiple instances of:

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/FixtureDocumentation.scala[tags=complex, indent=-]
----

== Benchmarking

Benchmarking in this module accepts an implicit `DurationFormat` function that accepts scala ``Duration``s. The
`failIfLongerThan` function also accepts scala ``Duration``s. The functionality remains the same as the java module.

[source, scala]
----
include::../core/src/test/scala/io/github/olib963/javatest_scala/documentation/BenchmarkDocumentation.scala[tags=include, indent=-]
----
